### PR TITLE
change png of Arcadia so its dark mode compatible

### PR DESCRIPTION
**Pull request by taylorreiter**
Thanks to @meganhoch to identifying this problem and making the new png!

@mertcelebi i also made the image smaller, feel free to tweak more. 

Of the three of us, I have the least design chops so default to both of your opinions!

### CODE REVIEW

**Review by mertcelebi — COMMENTED** [review]
What does it mean that the png is dark mode compatible? Like does it change background? It only seems like now there's a darker hue to the background. 

Also can we crop the image tightly around the text?

**Comment by taylorreiter** [comment]
Screenshot 2023-05-03 at 2 41 49 PM

it looked like the above for megan. 

I'm fine with cropping! I'll let megan chime in if that's ok, and let me know if she wants me to take care of it or would like to do it

**Comment by taylorreiter** [comment]
ok @mertcelebi @meganhoch how does that look?

**Review by meganhoch — COMMENTED** [review]
IMG_1246

Not sure if this is just an issue with the preview, but the image shows up like this on my phone. I think it looks good otherwise!

**Comment by taylorreiter** [comment]
Ok @meganhoch this should now be fixed for light and dark mode and web and phone viewing. the logo is large, but it won't look distorted on different viewing environments.

**Review by meganhoch — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
